name: branch-diff # you probably want to 'snapcraft register <name>'
version: 1.7.0  # just for humans, typically '1.2+git' or '1.3.2'
summary: Compares 2 git branches without hassle.
description: |
    A tool to list print the commits on one git branch 
    that are not on another using loose comparison.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
    branch-diff:
        command: bin/branch-diff
        plugs: [network]

parts:
  branch-diff:
    source: https://github.com/nodejs/branch-diff.git 
    source-tag: v1.7.0
    # See 'snapcraft plugins'
    plugin: nodejs
