name: branch-diff
version: 1.7.0
summary: Compares 2 git branches without hassle.
description: |
    A tool to list print the commits on one git branch 
    that are not on another using loose comparison.
grade: stable
confinement: strict

apps:
    branch-diff:
        command: bin/branch-diff
        plugs: [network, home]

parts:
  branch-diff:
    source: https://github.com/nodejs/branch-diff.git 
    source-tag: v1.7.0
    plugin: nodejs
  git:
      source: https://github.com/git/git.git
      source-tag: v2.15.1
      plugin: autotools

